name: Deploy

on: 
  push:
    branches:
      - master

jobs:
  deploy-ec2:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@master
    - name: Upload to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_IP }}
        key: ${{ secrets.EC2_KEY }}
        username: ec2-user
        source: "*"
        target: "server"
        rm: true
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      env:
        host: ${{ secrets.EC2_IP }}
        key: ${{ secrets.EC2_KEY }}
        username: ec2-user
        script: sudo systemctl restart server.service
